# Generated by Django 4.1.3 on 2022-11-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('matricula', models.IntegerField()),
                ('curso', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('resumo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_fc.aluno')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_fc.livro')),
            ],
        ),
    ]
